### ISSUE TITLE
Scsynth not found.

### ISSUE THREAD

**Issue by Cricot2** [smrg-lm/sc3#5]
Hello, 
First this project look really interesting. Something you dream at night when you begin in Python and Supercollider...
And you did it! i love the transcription between the two laguage.

I wanted to test and get this error (with your example script) :
`ERROR:sc3.synth.server:localhost failed to boot, program scsynth not found`

I'm on mac OS Catalina. 
Python3.7.4
SuperCollider 3.11.2
My regular SuperCollider app is in `/Applications/SuperCollider`.
I copied this app to this path to : `/Users/macbook/Applications/SuperCollider` but same result...

got sc3 from source code in develop mode (everything goes fine).

For info i can use without problem an other SuperCollider / Pyhton project => [supercollider](https://pypi.org/project/supercollider/) and start SC server within VS-Code. So i'am wondering why it doesn't find my Scsynth program?

Thank you very much. I hope to test it soon ! 
Michaël Filler.

**Comment by Cricot2** [comment]
Solved...

In `/base/platform.py` line 217 : 
Changed with my correct path:
`self._installation_dir = '/Applications/SuperCollider/SuperCollider.app'`

Because wen i install SC from the official repo the app goes in a folder named SuperCollider...
Michaël Filler.

**Comment by smrg-lm** [comment]
Thank you

It is not necessary to edit the source code, you can specify it by setting `Platform.installation_dir` or directly `s.options.program`, there is also a setup file. I wrote a simple explanation here:

https://sc3.readthedocs.io/en/latest/intro/server.html
